config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end
  resources :users
  resource :session, only: [:new, :create, :destroy]
  root to: redirect('/cats')
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :username, :session_token, uniqueness: true, presence: true
  validates :password_digest, presence: true
  
  after_initialize :ensure_session_token
  
  attr_reader :password
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil unless @user
    @user.is_password?(password) ? @user : nil
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_out
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save!
      login!(@user)
      redirect_to cats_url
    # else
    #   flash[:error] = ["Incorrect username and/or password"]
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
    
  end
end

app/views/users/_form.html.erb
<% action_url = (action == "login" ? session_url : users_url) %>
<% text = (action == "login" ? "LOG IN" : "SIGN UP") %>


<h1><%= text %></h1>

<form class="" action="<%= action_url %>" method="post">
  
  <label for="username">Username: </label>
  <input
  type="text"
  name="user[username]"
  id="username"
  value="<%= user.username %>">
  <br>
  
  <label for="password">Password: </label>
  <input
  type="password"
  name="user[password]"
  id="password"
  value="<%= user.password %>">
  
  <input type="submit" value="<%= text %>">
</form>

app/views/users/new.html.erb
<!-- users new.html -->
<%= render 'form', user: @user, action: "signup" %>